modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="stevespantry"
version="0.1.0"
displayName="Steve's Pantry"
authors="awweaver"
description='''
Spices from around the world and dishes you assemble yourself, Tinkers' style.
Dishes go stale and spoil, so cook what you'll eat. Pairs with Pam's HarvestCraft 2.
'''

[[dependencies.stevespantry]]
    modId="forge"
    mandatory=true
    versionRange="[43.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stevespantry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stevespantry]]
    modId="pamhc2crops"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.stevespantry]]
    modId="pamhc2trees"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
